import { Header } from '../sections/Header/Header';
import './globals.css';
import { Footer } from '../sections/Footer/Footer';
import StoreProvider from './StoreProvider';
import { MainPage } from '../sections/Main/MainPage';
import TokenChecker from '../sections/TokenChecker/TokenChecker';

export const metadata = {
  title: {
    default: 'Нечупара- магазин дитячих товарів',
    template: '%s | Нечупара',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-w-full min-h-full">
        <StoreProvider>
          <TokenChecker>
            <Header />
            <MainPage>{children}</MainPage>
            <Footer />
          </TokenChecker>
        </StoreProvider>
      </body>
    </html>
  );
}
